"use client";

import type { ClubDetail } from "@dartflow/shared";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useCloud } from "@/components/cloud/CloudProvider";
import { SelectField } from "@/components/ui/SelectField";
import { apiRequest } from "@/src/cloud/api";

export function ClubDetailScreen({ clubId }: { clubId: string }) {
  const router = useRouter(); const { user } = useCloud();
  const [detail,setDetail]=useState<ClubDetail|null>(null); const [message,setMessage]=useState(""); const [guestName,setGuestName]=useState(""); const [profileId,setProfileId]=useState("");
  const refresh=useCallback(async()=>setDetail(await apiRequest<ClubDetail>(`/clubs/${clubId}`)),[clubId]);
  useEffect(()=>{let active=true;void apiRequest<ClubDetail>(`/clubs/${clubId}`).then(result=>{if(active)setDetail(result);}).catch(error=>{if(active)setMessage(error instanceof Error?error.message:"Club inaccessible.");});return()=>{active=false;};},[clubId]);
  const action=async(task:()=>Promise<unknown>,success:string)=>{setMessage("");try{await task();setMessage(success);await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Action impossible.");}};
  const createGuest=async(event:FormEvent)=>{event.preventDefault();await action(()=>apiRequest(`/clubs/${clubId}/guest-profiles`,{method:"POST",body:JSON.stringify({name:guestName})}),"Profil invité créé.");setGuestName("");};
  const deleteClub=async()=>{if(!window.confirm("Supprimer définitivement ce club ? Les profils invités seront supprimés et les parties resteront dans l’historique personnel."))return;try{await apiRequest(`/clubs/${clubId}`,{method:"DELETE"});router.push("/clubs");}catch(error){setMessage(error instanceof Error?error.message:"Suppression impossible.");}};
  if(!detail)return <main className="mx-auto min-h-screen max-w-5xl px-4 py-8"><p className="text-[var(--muted)]">{message||"Chargement…"}</p></main>;
  const {club,members,profiles,availableProfiles}=detail; const admin=club.role==="owner"||club.role==="admin"; const pending=members.filter(member=>member.status==="pending"); const active=members.filter(member=>member.status==="active"); const selected=availableProfiles.some(profile=>profile.id===profileId)?profileId:availableProfiles[0]?.id??"";
  return <main className="mx-auto min-h-screen max-w-6xl px-4 py-8 sm:px-7">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/clubs" className="text-sm font-bold text-[var(--muted)]">← Tous les clubs</Link><p className="mt-5 text-xs font-black uppercase tracking-[.18em] text-[var(--lime)]">Club · {club.visibility}</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">{club.name}</h1><p className="mt-2 max-w-2xl text-[var(--muted)]">{club.description||"Aucune description"}</p></div><div className="flex flex-wrap gap-2"><Link href={`/clubs/${club.id}/stats`} className="grid min-h-13 place-items-center rounded-xl border border-[var(--lime)] px-5 font-black text-[var(--lime)]">Classement et stats</Link>{profiles.length?<Link href={`/new-game?club=${club.id}`} className="grid min-h-13 place-items-center rounded-xl bg-[var(--lime)] px-6 font-black text-black">Jouer dans ce club →</Link>:<span className="rounded-xl border border-[var(--line)] px-4 py-3 text-sm text-[var(--muted)]">Ajoute un profil pour jouer</span>}</div></div>
    {message&&<p role="status" className="mt-5 rounded-xl border border-[var(--line)] p-3 text-sm text-[var(--muted)]">{message}</p>}
    {admin&&<section className="mt-8 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-5"><p className="text-xs font-black uppercase tracking-[.15em] text-[var(--lime)]">Invitation</p><p className="mt-2 text-sm text-[var(--muted)]">Toute personne possédant ce code rejoint immédiatement le club.</p><div className="mt-3 flex gap-2"><code className="min-w-0 flex-1 rounded-xl bg-black/30 px-4 py-3 font-black tracking-wider">{club.inviteCode}</code><button onClick={()=>void action(()=>apiRequest(`/clubs/${clubId}/invite-code`,{method:"POST"}),"Nouveau code généré.")} className="rounded-xl border border-[var(--line)] px-4 text-sm font-bold">Renouveler</button></div></div><div className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-5"><p className="text-xs font-black uppercase tracking-[.15em] text-[var(--lime)]">Accès</p><p className="mt-2 font-bold">{club.visibility==="public"?"Club public":"Club privé"}</p><button onClick={()=>void action(()=>apiRequest(`/clubs/${clubId}`,{method:"PATCH",body:JSON.stringify({visibility:club.visibility==="public"?"private":"public"})}),"Visibilité modifiée.")} className="mt-3 rounded-xl border border-[var(--line)] px-4 py-2 text-sm font-bold">Passer en {club.visibility==="public"?"privé":"public"}</button>{club.role==="owner"&&<button onClick={()=>void deleteClub()} className="ml-2 mt-3 rounded-xl border border-[#713b32] px-4 py-2 text-sm font-bold text-[#ff9b7a]">Supprimer le club</button>}</div></section>}
    {pending.length>0&&admin&&<section className="mt-8"><h2 className="text-2xl font-black">Demandes d’adhésion</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{pending.map(member=><div key={member.userId} className="flex items-center justify-between rounded-xl border border-[var(--line)] bg-[var(--panel)] p-4"><strong>@{member.username}</strong><div className="flex gap-2"><button onClick={()=>void action(()=>apiRequest(`/clubs/${clubId}/members/${member.userId}/approve`,{method:"POST"}),"Membre accepté.")} className="rounded-lg bg-[var(--lime)] px-3 py-2 text-sm font-black text-black">Accepter</button><button onClick={()=>void action(()=>apiRequest(`/clubs/${clubId}/members/${member.userId}`,{method:"DELETE"}),"Demande refusée.")} className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm font-bold">Refuser</button></div></div>)}</div></section>}
    <section className="mt-10"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[var(--lime)]">Joueurs</p><h2 className="mt-1 text-3xl font-black">Profils du club</h2></div><span className="text-sm text-[var(--muted)]">{profiles.length} profil{profiles.length>1?"s":""}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{profiles.map(profile=><article key={profile.id} className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-4"><div className="flex items-center justify-between gap-3"><div><strong>{profile.name}</strong><p className="text-xs text-[var(--muted)]">{profile.kind==="guest"?`Invité · ${profile.ownerUsername}`:`@${profile.ownerUsername}`}</p></div>{profile.canManage&&<button onClick={()=>void action(()=>apiRequest(`/clubs/${clubId}/profiles/${profile.id}`,{method:"DELETE"}),"Profil retiré du club.")} className="text-sm font-bold text-[#ff9b7a]">Retirer</button>}</div></article>)}</div>
      <div className="mt-5 grid gap-3 md:grid-cols-2"><form onSubmit={(event)=>{event.preventDefault();if(selected)void action(()=>apiRequest(`/clubs/${clubId}/profiles/${selected}`,{method:"POST"}),"Profil partagé avec le club.");}} className="rounded-2xl border border-[var(--line)] p-4"><h3 className="font-black">Partager un profil privé</h3><p className="mt-1 text-sm text-[var(--muted)]">Tous les membres pourront l’utiliser, sans pouvoir le modifier.</p>{availableProfiles.length?<div className="mt-3 flex gap-2"><div className="min-w-0 flex-1"><SelectField compact value={selected} ariaLabel="Profil à partager" options={availableProfiles.map(profile=>({value:profile.id,label:profile.name}))} onChange={setProfileId}/></div><button className="rounded-xl bg-[var(--lime)] px-4 font-black text-black">Partager</button></div>:<p className="mt-3 text-sm text-[var(--muted)]">Tous tes profils sont déjà partagés.</p>}</form><form onSubmit={createGuest} className="rounded-2xl border border-[var(--line)] p-4"><h3 className="font-black">Créer un profil invité</h3><p className="mt-1 text-sm text-[var(--muted)]">Pour une personne sans compte DartFlow.</p><div className="mt-3 flex gap-2"><input required maxLength={30} value={guestName} onChange={event=>setGuestName(event.target.value)} placeholder="Pseudo de l’invité" className="min-h-11 min-w-0 flex-1 rounded-xl border border-[var(--line)] bg-black/20 px-3"/><button className="rounded-xl border border-[var(--lime)] px-4 font-black text-[var(--lime)]">Créer</button></div></form></div>
    </section>
    <section className="mt-10"><h2 className="text-2xl font-black">Membres</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{active.map(member=><article key={member.userId} className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-4"><div className="flex items-center justify-between"><div><strong>@{member.username}</strong><p className="text-xs text-[var(--muted)]">{member.role}</p></div>{member.role!=="owner"&&<div className="flex gap-2">{club.role==="owner"&&member.userId!==user?.id&&<button onClick={()=>void action(()=>apiRequest(`/clubs/${clubId}/members/${member.userId}`,{method:"PATCH",body:JSON.stringify({role:member.role==="admin"?"member":"admin"})}),"Rôle modifié.")} className="text-xs font-bold text-[var(--lime)]">{member.role==="admin"?"Rétrograder":"Admin"}</button>}{(member.userId===user?.id||admin)&&<button onClick={()=>void action(()=>apiRequest(`/clubs/${clubId}/members/${member.userId}`,{method:"DELETE"}),member.userId===user?.id?"Tu as quitté le club.":"Membre retiré.").then(()=>{if(member.userId===user?.id)router.push("/clubs");})} className="text-xs font-bold text-[#ff9b7a]">{member.userId===user?.id?"Quitter":"Retirer"}</button>}</div>}</div></article>)}</div></section>
  </main>;
}
