"use client";

import type { ClubRoom } from "@dartflow/shared";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { onRealtime } from "@/components/realtime/RealtimeProvider";
import { apiRequest } from "@/src/cloud/api";

export function ClubRoomsScreen({ clubId }: { clubId: string }) {
  const router=useRouter();
  const [rooms,setRooms]=useState<ClubRoom[]>([]); const [name,setName]=useState("Table principale"); const [error,setError]=useState(""); const [creating,setCreating]=useState(false);
  const refresh=useCallback(async()=>{try{const result=await apiRequest<{rooms:ClubRoom[]}>(`/clubs/${clubId}/rooms`);setRooms(result.rooms);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Salons indisponibles.");}},[clubId]);
  useEffect(()=>{const timer=setTimeout(()=>void refresh(),0);const unsubscribe=onRealtime(event=>{if(event.type==="room.changed"&&event.clubId===clubId)void refresh();});return()=>{clearTimeout(timer);unsubscribe();};},[clubId,refresh]);
  const create=async(event:FormEvent)=>{event.preventDefault();if(creating)return;setCreating(true);try{const result=await apiRequest<{id:string}>(`/clubs/${clubId}/rooms`,{method:"POST",body:JSON.stringify({name})});router.push(`/clubs/${clubId}/live/${result.id}`);}catch(reason){setError(reason instanceof Error?reason.message:"Création impossible.");setCreating(false);}};
  return <main className="mx-auto min-h-screen max-w-5xl px-4 py-8 sm:px-7"><Link href={`/clubs/${clubId}`} className="text-sm font-bold text-[var(--muted)]">← Retour au club</Link><div className="mt-5 grid gap-6 lg:grid-cols-[1fr_20rem]"><section><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--lime)]">Parties synchronisées</p><h1 className="mt-2 text-4xl font-black">Salons en direct</h1><p className="mt-3 max-w-xl text-[var(--muted)]">Les membres peuvent suivre la partie depuis leur appareil pendant que le marqueur saisit les lancers.</p>{error&&<p role="alert" className="mt-4 text-[#ff9b7a]">{error}</p>}<div className="mt-6 grid gap-3">{rooms.length===0?<p className="rounded-2xl border border-[var(--line)] p-6 text-[var(--muted)]">Aucun salon ouvert.</p>:rooms.map(room=><Link key={room.id} href={`/clubs/${clubId}/live/${room.id}`} className="flex items-center justify-between gap-4 rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-4 hover:border-[var(--lime)]/50"><span><span className="flex items-center gap-2"><span className={`size-2 rounded-full ${room.status==="playing"?"animate-pulse bg-[#ff6b35]":room.status==="waiting"?"bg-[var(--lime)]":"bg-[var(--muted)]"}`}/><strong>{room.name}</strong></span><small className="mt-1 block text-[var(--muted)]">Marqueur : @{room.scorerUsername} · {room.viewerCount} spectateur{room.viewerCount>1?"s":""}</small></span><span className="text-xl text-[var(--lime)]">→</span></Link>)}</div></section><form onSubmit={create} className="h-fit rounded-2xl border border-[var(--lime)]/40 bg-[var(--panel)] p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-[var(--lime)]">Nouveau salon</p><label className="mt-4 block"><span className="mb-2 block text-sm font-bold">Nom</span><input required minLength={2} maxLength={80} value={name} onChange={event=>setName(event.target.value)} className="min-h-12 w-full rounded-xl border border-[var(--line)] bg-black/20 px-3"/></label><button disabled={creating} className="mt-4 min-h-12 w-full rounded-xl bg-[var(--lime)] font-black text-black disabled:opacity-50">{creating?"Création…":"Créer le salon"}</button></form></div></main>;
}
