"use client";

import type { LeaderboardRow } from "@dartflow/shared";
import Link from "next/link";
import { useEffect, useState } from "react";
import { SelectField } from "@/components/ui/SelectField";
import { apiRequest } from "@/src/cloud/api";

export function LeaderboardScreen() {
  const [mode, setMode] = useState(""); const [rows, setRows] = useState<LeaderboardRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; void apiRequest<{ rows: LeaderboardRow[] }>(`/leaderboard${mode ? `?mode=${encodeURIComponent(mode)}` : ""}`).then((result) => { if (active) setRows(result.rows); }).catch((caught) => { if (active) setError(caught instanceof Error ? caught.message : "Classement indisponible."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [mode]);
  return <main className="mx-auto min-h-screen max-w-4xl px-4 py-5 sm:px-7"><header className="mb-8 flex items-center justify-between border-b border-[var(--line)] pb-4"><Link href="/" className="font-bold text-[var(--muted)] hover:text-white">← Accueil</Link><span className="text-sm font-black tracking-[.14em]">CLASSEMENT</span></header><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--lime)]">Profils publics</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">Classement en ligne</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--muted)]">Les résultats proviennent de scores saisis manuellement : ce classement est amical et non certifié.</p><div className="mt-5 max-w-xs"><SelectField value={mode} ariaLabel="Mode du classement" options={[{ value: "", label: "Tous les modes" }, { value: "count-up", label: "Count-Up" }, { value: "x01", label: "X01" }, { value: "around-the-clock", label: "Around the Clock" }, { value: "shanghai", label: "Shanghai" }, { value: "cricket", label: "Cricket" }, { value: "killer", label: "Killer" }]} onChange={(value) => { setLoading(true); setError(""); setMode(value); }} /></div>{loading ? <p className="mt-6 text-[var(--muted)]">Chargement…</p> : error ? <p className="mt-6 text-[#ff9b7a]">{error}</p> : rows.length === 0 ? <p className="mt-6 rounded-2xl border border-[var(--line)] p-5 text-[var(--muted)]">Aucun profil public n’a encore terminé de partie dans ce mode.</p> : <div className="mt-6 overflow-hidden rounded-2xl border border-[var(--line)]"><div className="grid grid-cols-[3rem_1fr_4rem_5rem] gap-2 bg-[var(--panel)] px-4 py-3 text-xs font-black uppercase tracking-wider text-[var(--muted)] sm:grid-cols-[3rem_1fr_6rem_6rem_6rem]"><span>#</span><span>Joueur</span><span>Victoires</span><span>Moy./dart</span><span className="hidden sm:block">Parties</span></div>{rows.map((row) => <div key={row.profileId} className="grid grid-cols-[3rem_1fr_4rem_5rem] items-center gap-2 border-t border-[var(--line)] px-4 py-4 sm:grid-cols-[3rem_1fr_6rem_6rem_6rem]"><strong className="text-[var(--lime)]">{row.rank}</strong><div className="min-w-0"><strong className="block truncate">{row.name}</strong><span className="text-xs text-[var(--muted)]">{row.winRate.toFixed(0)} %</span></div><strong>{row.wins}</strong><strong>{row.averagePerDart.toFixed(1)}</strong><span className="hidden sm:block">{row.games}</span></div>)}</div>}</main>;
}
