import { z } from "zod";

export const playerSchema = z.object({ id: z.string().min(1), name: z.string().trim().min(1).max(40), color: z.string().optional(), avatar: z.string().optional(), order: z.number().int().min(0).max(7) });
export const countUpConfigSchema = z.object({ rounds: z.number().int().min(1).max(99), players: z.array(playerSchema).min(1).max(8) });
export const x01ConfigSchema = z.object({ startingScore: z.union([z.literal(301), z.literal(501), z.literal(701)]), entryRule: z.enum(["straight", "double", "master"]), exitRule: z.enum(["straight", "double", "master"]), rounds: z.number().int().min(1).max(99).nullable(), players: z.array(playerSchema).min(1).max(8) });
export const aroundTheClockConfigSchema = z.object({ progressionRule: z.enum(["single-only", "multiplier"]), bullFinish: z.boolean(), rounds: z.number().int().min(1).max(99).nullable(), players: z.array(playerSchema).min(1).max(8) });
export const shanghaiConfigSchema = z.object({ rounds: z.number().int().min(1).max(20), instantShanghaiWin: z.boolean(), players: z.array(playerSchema).min(1).max(8) });
export const cricketConfigSchema = z.object({ rounds: z.number().int().min(1).max(99).nullable(), players: z.array(playerSchema).min(1).max(8) });
export const killerConfigSchema = z.object({ lives: z.number().int().min(1).max(5), players: z.array(playerSchema).min(2).max(8) });

const dartSchema = z.object({ id: z.string(), segment: z.number().int().min(1).max(20).nullable(), multiplier: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3)]), score: z.number().int().min(0).max(60), zone: z.enum(["miss", "single-inner", "single-outer", "double", "triple", "outer-bull", "inner-bull"]), thrownAt: z.string() });
const turnSchema = z.object({ id: z.string(), playerId: z.string(), roundNumber: z.number().int().positive(), darts: z.array(dartSchema).max(3), scoreBeforeTurn: z.number(), scoreAfterTurn: z.number(), turnScore: z.number(), isBust: z.boolean(), isCompleted: z.boolean(), createdAt: z.string() });
const countUpStateSchema = z.object({ kind: z.literal("count-up"), maxRounds: z.number().int().positive(), scores: z.record(z.string(), z.number()) });
const x01StateSchema = z.object({ kind: z.literal("x01"), startingScore: z.union([z.literal(301), z.literal(501), z.literal(701)]), entryRule: z.enum(["straight", "double", "master"]), exitRule: z.enum(["straight", "double", "master"]), maxRounds: z.number().int().positive().nullable(), players: z.record(z.string(), z.object({ score: z.number().int().min(0), hasEntered: z.boolean() })) });
const aroundTheClockStateSchema = z.object({ kind: z.literal("around-the-clock"), progressionRule: z.enum(["single-only", "multiplier"]), bullFinish: z.boolean(), maxRounds: z.number().int().positive().nullable(), players: z.record(z.string(), z.object({ target: z.number().int().min(1).max(21), completed: z.boolean() })) });
const shanghaiStateSchema = z.object({ kind: z.literal("shanghai"), maxRounds: z.number().int().min(1).max(20), instantShanghaiWin: z.boolean(), scores: z.record(z.string(), z.number()) });
const cricketMarksSchema = z.object({ 20: z.number().int().min(0).max(3), 19: z.number().int().min(0).max(3), 18: z.number().int().min(0).max(3), 17: z.number().int().min(0).max(3), 16: z.number().int().min(0).max(3), 15: z.number().int().min(0).max(3), bull: z.number().int().min(0).max(3) });
const cricketStateSchema = z.object({ kind: z.literal("cricket"), maxRounds: z.number().int().positive().nullable(), players: z.record(z.string(), z.object({ score: z.number().min(0), marks: cricketMarksSchema })) });
const killerStateSchema = z.object({ kind: z.literal("killer"), startingLives: z.number().int().min(1).max(5), marksToKiller: z.literal(3), players: z.record(z.string(), z.object({ number: z.number().int().min(1).max(20), marks: z.number().int().min(0).max(3), isKiller: z.boolean(), lives: z.number().int().min(0).max(5), eliminated: z.boolean() })) });
export const gameStateSchema = z.object({ id: z.string(), modeId: z.enum(["count-up", "x01", "around-the-clock", "shanghai", "cricket", "killer"]), status: z.enum(["setup", "in-progress", "paused", "completed", "cancelled"]), players: z.array(playerSchema).min(1).max(8), currentPlayerIndex: z.number().int().min(0).max(7), currentRound: z.number().int().positive(), currentTurn: turnSchema, turns: z.array(turnSchema), modeState: z.discriminatedUnion("kind", [countUpStateSchema, x01StateSchema, aroundTheClockStateSchema, shanghaiStateSchema, cricketStateSchema, killerStateSchema]), winnerId: z.string().optional(), createdAt: z.string(), updatedAt: z.string(), completedAt: z.string().optional() });
