"use client";

import type { FriendSummary, FriendsResponse, ProfileShare } from "@dartflow/shared";
import Image from "next/image";
import Link from "next/link";
import { ChangeEvent, FormEvent, useCallback, useEffect, useState } from "react";
import { useCloud } from "@/components/cloud/CloudProvider";
import { SelectField } from "@/components/ui/SelectField";
import { apiRequest } from "@/src/cloud/api";
import type { SavedPlayer } from "@/src/database/database";
import { loadPlayers } from "@/src/database/repositories/player-repository";
import { prepareAvatar } from "@/src/images/prepare-avatar";

function ProfileSharing({ profile, friends }: { profile: SavedPlayer; friends: FriendSummary[] }) {
  const [friendId,setFriendId]=useState(""); const [role,setRole]=useState<"player"|"manager">("player"); const [shares,setShares]=useState<ProfileShare[]>([]); const [message,setMessage]=useState("");
  const refresh=useCallback(async()=>{const result=await apiRequest<{shares:ProfileShare[]}>(`/profiles/${profile.id}/shares`);setShares(result.shares);},[profile.id]);
  useEffect(()=>{let active=true;void apiRequest<{shares:ProfileShare[]}>(`/profiles/${profile.id}/shares`).then(result=>{if(active)setShares(result.shares);}).catch(()=>undefined);return()=>{active=false;};},[profile.id]);
  const available=friends.filter(friend=>!shares.some(share=>share.userId===friend.userId)); const selected=available.some(friend=>friend.userId===friendId)?friendId:available[0]?.userId??"";
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!selected)return;setMessage("");try{await apiRequest(`/profiles/${profile.id}/shares`,{method:"POST",body:JSON.stringify({userId:selected,role})});setFriendId("");setMessage("Profil partagé.");await refresh();}catch(caught){setMessage(caught instanceof Error?caught.message:"Partage impossible.");}};
  return <div className="mt-4 border-t border-[var(--line)] pt-4"><p className="mb-2 text-xs font-black uppercase tracking-[.12em] text-[var(--muted)]">Accès des amis</p>{available.length>0?<form onSubmit={submit} className="grid gap-2 sm:grid-cols-[1fr_10rem_auto]"><SelectField compact value={selected} ariaLabel="Ami destinataire" options={available.map(friend=>({value:friend.userId,label:`@${friend.username}`}))} onChange={setFriendId}/><SelectField compact value={role} ariaLabel="Droit accordé" options={[{value:"player",label:"Utiliser"},{value:"manager",label:"Gérer"}]} onChange={value=>setRole(value as "player"|"manager")}/><button className="min-h-11 rounded-xl bg-[var(--lime)] px-4 font-black text-black">Partager</button></form>:<p className="text-sm text-[var(--muted)]">{friends.length?"Tous tes amis ont déjà accès à ce profil.":"Ajoute un ami pour lui donner accès à ce profil."}</p>}{message&&<p className="mt-2 text-sm text-[var(--muted)]">{message}</p>}{shares.length>0&&<div className="mt-3 space-y-2">{shares.map(share=><div key={share.userId} className="flex items-center justify-between rounded-lg bg-black/20 px-3 py-2 text-sm"><span>@{share.username} · {share.role==="manager"?"peut gérer":"peut utiliser"}</span><button type="button" onClick={()=>void apiRequest<void>(`/profiles/${profile.id}/shares/${share.userId}`,{method:"DELETE"}).then(refresh)} className="font-bold text-[#ff9b7a]">Retirer</button></div>)}</div>}</div>;
}

export function AccountScreen(){
  const{user,loading,logout,syncNow,syncStatus,lastSyncedAt,updateUsername,updateAvatar}=useCloud();
  const[profiles,setProfiles]=useState<SavedPlayer[]>([]);const[friendsData,setFriendsData]=useState<FriendsResponse>({friends:[],requests:[]});const[friendQuery,setFriendQuery]=useState("");const[foundUsers,setFoundUsers]=useState<Array<{userId:string;username:string}>>([]);const[message,setMessage]=useState("");const[username,setUsername]=useState("");const[avatarBusy,setAvatarBusy]=useState(false);
  const refreshFriends=useCallback(async()=>{const result=await apiRequest<FriendsResponse>("/friends");setFriendsData(result);},[]);
  useEffect(()=>{if(!user)return;let active=true;void loadPlayers().then(result=>{if(active)setProfiles(result);});return()=>{active=false;};},[user,lastSyncedAt]);
  useEffect(()=>{if(!user)return;let active=true;void apiRequest<FriendsResponse>("/friends").then(result=>{if(active)setFriendsData(result);}).catch(()=>undefined);return()=>{active=false;};},[user]);
  const search=async(event:FormEvent)=>{event.preventDefault();setMessage("");try{const result=await apiRequest<{users:Array<{userId:string;username:string}>}>(`/friends/search?q=${encodeURIComponent(friendQuery)}`);setFoundUsers(result.users);if(!result.users.length)setMessage("Aucun compte trouvé.");}catch(caught){setMessage(caught instanceof Error?caught.message:"Recherche impossible.");}};
  const requestFriend=async(usernameValue:string)=>{try{await apiRequest("/friends/requests",{method:"POST",body:JSON.stringify({username:usernameValue})});setFoundUsers([]);setFriendQuery("");setMessage(`Demande envoyée à @${usernameValue}.`);await refreshFriends();}catch(caught){setMessage(caught instanceof Error?caught.message:"Demande impossible.");}};
  const accept=async(userId:string)=>{await apiRequest(`/friends/requests/${userId}/accept`,{method:"POST"});await refreshFriends();};
  const remove=async(userId:string)=>{if(!window.confirm("Retirer cette relation et les profils partagés ?"))return;await apiRequest(`/friends/${userId}`,{method:"DELETE"});await refreshFriends();await syncNow();};
  const changeUsername=async(event:FormEvent)=>{event.preventDefault();setMessage("");try{await updateUsername(username);setUsername("");setMessage("Nom d’utilisateur mis à jour.");}catch(caught){setMessage(caught instanceof Error?caught.message:"Modification impossible.");}};
  const changeAvatar=async(event:ChangeEvent<HTMLInputElement>)=>{const input=event.currentTarget;const file=input.files?.[0];input.value="";if(!file)return;setAvatarBusy(true);setMessage("");try{await updateAvatar(await prepareAvatar(file));setMessage("Photo de profil mise à jour.");}catch(caught){setMessage(caught instanceof Error?caught.message:"Modification impossible.");}finally{setAvatarBusy(false);}};
  const removeAvatar=async()=>{setAvatarBusy(true);setMessage("");try{await updateAvatar(null);setMessage("Photo de profil supprimée.");}catch(caught){setMessage(caught instanceof Error?caught.message:"Suppression impossible.");}finally{setAvatarBusy(false);}};
  const togglePublic=async(profile:SavedPlayer)=>{try{await apiRequest(`/profiles/${profile.id}`,{method:"PATCH",body:JSON.stringify({isPublic:!profile.isPublic})});await syncNow();}catch(caught){setMessage(caught instanceof Error?caught.message:"Modification impossible.");}};
  if(loading)return <main className="grid min-h-screen place-items-center"><p className="text-[var(--muted)]">Chargement…</p></main>;
  if(!user)return <main className="mx-auto min-h-screen max-w-lg px-4 py-8"><section className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-6 text-center"><h1 className="text-3xl font-black">Connecte-toi à DartFlow</h1><p className="mt-2 text-[var(--muted)]">Synchronise tes profils et joue avec ceux de tes amis.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Link href="/login" className="grid min-h-12 place-items-center rounded-xl border-2 border-[var(--lime)] font-black text-[var(--lime)]">Connexion</Link><Link href="/register" className="grid min-h-12 place-items-center rounded-xl bg-[var(--lime)] font-black text-black">Inscription</Link></div></section></main>;
  return <main className="mx-auto min-h-screen max-w-5xl px-4 py-8 sm:px-7"><section className="rounded-[1.6rem] border border-[var(--line)] bg-[var(--panel)] p-5"><div className="flex flex-wrap items-start justify-between gap-5"><div className="flex flex-wrap items-center gap-4"><div className="relative grid size-24 shrink-0 place-items-center overflow-hidden rounded-full border-2 border-[var(--lime)]/50 bg-black/30">{user.avatar?<Image src={user.avatar} alt={`Photo de ${user.username}`} fill sizes="96px" unoptimized className="object-cover"/>:<span className="text-3xl font-black uppercase text-[var(--lime)]">{user.username.charAt(0)}</span>}</div><div><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--lime)]">Compte connecté</p><h1 className="mt-2 text-3xl font-black">@{user.username}</h1><p className="text-sm text-[var(--muted)]">{user.email}</p><p className="mt-2 text-xs text-[var(--muted)]">{syncStatus==="syncing"?"Synchronisation…":syncStatus==="offline"?"Hors ligne · changements conservés":lastSyncedAt?`Synchronisé ${new Date(lastSyncedAt).toLocaleString("fr-FR")}`:"Prêt à synchroniser"}</p><div className="mt-3 flex flex-wrap items-center gap-2"><label className={`cursor-pointer rounded-xl bg-[var(--lime)] px-4 py-2 text-sm font-black text-black ${avatarBusy?"pointer-events-none opacity-50":""}`}>{avatarBusy?"Préparation…":user.avatar?"Changer la photo":"Ajouter une photo"}<input type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" aria-label="Choisir une photo de profil" disabled={avatarBusy} onChange={changeAvatar} className="sr-only"/></label>{user.avatar&&<button type="button" disabled={avatarBusy} onClick={()=>void removeAvatar()} className="rounded-xl border border-[var(--line)] px-4 py-2 text-sm font-bold text-[#ff9b7a] disabled:opacity-50">Supprimer</button>}</div><p className="mt-2 text-[11px] text-[var(--muted)]">JPG, PNG ou WebP · 5 Mo maximum</p></div></div><div className="flex gap-2"><button onClick={()=>void syncNow()} className="rounded-xl border border-[var(--line)] px-4 py-2 font-bold">Synchroniser</button><button onClick={()=>void logout()} className="rounded-xl border border-[#713b32] px-4 py-2 font-bold text-[#ff9b7a]">Déconnexion</button></div></div><form onSubmit={changeUsername} className="mt-5 flex max-w-md gap-2"><div className="flex min-h-11 min-w-0 flex-1 items-center rounded-xl border border-[var(--line)] bg-[#0d0f0e] px-3"><span className="text-[var(--muted)]">@</span><input value={username} onChange={event=>setUsername(event.target.value)} placeholder="nouveau_pseudo" minLength={3} maxLength={24} pattern="[A-Za-z0-9_]+" className="min-w-0 flex-1 bg-transparent px-1 outline-none"/></div><button className="rounded-xl border border-[var(--line)] px-4 font-bold">Modifier</button></form>{message&&<p className="mt-3 text-sm text-[var(--muted)]">{message}</p>}</section>
  <section id="friends" className="mt-8 scroll-mt-5"><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--lime)]">Réseau</p><h2 className="mt-2 text-3xl font-black">Mes amis</h2><form onSubmit={search} className="mt-4 flex max-w-xl gap-2"><div className="flex min-h-12 min-w-0 flex-1 items-center rounded-xl border border-[var(--line)] bg-[var(--panel)] px-4"><span className="text-[var(--muted)]">@</span><input required minLength={2} value={friendQuery} onChange={event=>setFriendQuery(event.target.value)} placeholder="rechercher_un_compte" className="min-w-0 flex-1 bg-transparent px-1 outline-none"/></div><button className="rounded-xl bg-[var(--lime)] px-5 font-black text-black">Rechercher</button></form>{foundUsers.length>0&&<div className="mt-3 max-w-xl space-y-2">{foundUsers.map(found=><div key={found.userId} className="flex items-center justify-between rounded-xl border border-[var(--line)] bg-[var(--panel)] p-3"><strong>@{found.username}</strong><button onClick={()=>void requestFriend(found.username)} className="rounded-lg border border-[var(--lime)] px-3 py-1.5 text-sm font-bold text-[var(--lime)]">Ajouter</button></div>)}</div>}{friendsData.requests.length>0&&<div className="mt-5 grid gap-2 sm:grid-cols-2">{friendsData.requests.map(request=><div key={request.userId} className="rounded-xl border border-[var(--line)] bg-[var(--panel)] p-4"><strong>@{request.username}</strong><p className="mt-1 text-xs text-[var(--muted)]">{request.direction==="incoming"?"Souhaite devenir ton ami":"Demande envoyée"}</p><div className="mt-3 flex gap-2">{request.direction==="incoming"&&<button onClick={()=>void accept(request.userId)} className="rounded-lg bg-[var(--lime)] px-3 py-1.5 text-sm font-black text-black">Accepter</button>}<button onClick={()=>void remove(request.userId)} className="rounded-lg border border-[var(--line)] px-3 py-1.5 text-sm font-bold">{request.direction==="incoming"?"Refuser":"Annuler"}</button></div></div>)}</div>}<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{friendsData.friends.map(friend=><article key={friend.userId} className="flex items-center justify-between rounded-xl border border-[var(--line)] bg-[var(--panel)] p-4"><div><strong>@{friend.username}</strong><p className="text-xs text-[var(--muted)]">Ami</p></div><button onClick={()=>void remove(friend.userId)} className="text-sm font-bold text-[#ff9b7a]">Retirer</button></article>)}{!friendsData.friends.length&&!friendsData.requests.length&&<p className="text-sm text-[var(--muted)]">Recherche un compte pour ajouter ton premier ami.</p>}</div></section>
  <section className="mt-10"><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--lime)]">Profils</p><h2 className="mt-2 text-3xl font-black">Accès et classement</h2><div className="mt-4 space-y-3">{profiles.map(profile=><article key={profile.id} className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-4"><div className="flex items-center justify-between gap-3"><div><strong>{profile.name}</strong><p className="mt-1 text-xs text-[var(--muted)]">{profile.cloudRole==="owner"||!profile.cloudRole?`Ton profil · @${user.username}`:`Partagé par @${profile.ownerUsername??"ami"} · ${profile.cloudRole==="manager"?"gestion":"utilisation"}`}</p></div>{(profile.cloudRole==="owner"||!profile.cloudRole)&&<button onClick={()=>void togglePublic(profile)} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${profile.isPublic?"border-[var(--lime)] text-[var(--lime)]":"border-[var(--line)] text-[var(--muted)]"}`}>{profile.isPublic?"Classement public":"Profil privé"}</button>}</div>{(profile.cloudRole==="owner"||!profile.cloudRole)&&<ProfileSharing profile={profile} friends={friendsData.friends}/>}</article>)}</div></section></main>;
}
